// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/laptop": {
            "post": {
                "description": "Create a new laptop",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "laptops"
                ],
                "summary": "Create a laptop",
                "parameters": [
                    {
                        "description": "Laptop",
                        "name": "laptop",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CRUD_API_pkg_model.Laptops"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created Laptop Successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/laptop/:laptopBrand": {
            "delete": {
                "description": "Delete a laptop by brand",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "laptops"
                ],
                "summary": "Delete a laptop",
                "parameters": [
                    {
                        "description": "Laptop",
                        "name": "laptop",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CRUD_API_pkg_model.Laptops"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/laptops/:laptopBrand": {
            "get": {
                "description": "Retrieve a list of laptops by brand",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "laptops"
                ],
                "summary": "Get laptops by brand",
                "parameters": [
                    {
                        "description": "Laptop",
                        "name": "laptop",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CRUD_API_pkg_model.Laptops"
                        }
                    }
                ],
                "responses": {}
            },
            "put": {
                "description": "Update the details of a laptop by brand",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "laptops"
                ],
                "summary": "Update a laptop by brand",
                "parameters": [
                    {
                        "description": "Laptop",
                        "name": "laptop",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CRUD_API_pkg_model.Laptops"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "CRUD_API_pkg_model.Laptops": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
